SHOW DATABASES;

CREATE DATABASE tutorial;

USE tutorial;

CREATE TABLE CLIENTE
(
	id SMALLINT UNSIGNED NOT NULL, /* NOT NULL dispensavel por ser uma PK */
	nome VARCHAR(60) NOT NULL,
	fone CHAR(10),
	PRIMARY KEY (id)
) ENGINE = InnoDB;


DESCRIBE CLIENTE;

CREATE TABLE PEDIDO
(
	id SMALLINT UNSIGNED NOT NULL,
	data DATE NOT NULL,
	valor NUMERIC (10, 2) NOT NULL,
	id_cliente SMALLINT UNSIGNED NOT NULL,
	PRIMARY KEY (id)
) ENGINE = InnoDB;

ALTER TABLE PEDIDO 
	ADD FOREIGN KEY (id_cliente) REFERENCES CLIENTE (id) 
	ON DELETE RESTRICT ON UPDATE RESTRICT;

DESCRIBE PEDIDO;
